
set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER clang-18)
set(CMAKE_C_COMPILER_TARGET x86_64-pc-linux-gnu)
set(CMAKE_CXX_COMPILER clang++-18)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-linux-gnu)

set(CMAKE_LINKER_TYPE LLD)
