
if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    set(CMAKE_SYSTEM_NAME Linux)
endif()
if(NOT CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "aarch64")
    set(CMAKE_SYSTEM_PROCESSOR aarch64)
    set(CMAKE_C_COMPILER_TARGET aarch64-linux-gnu)
    set(CMAKE_CXX_COMPILER_TARGET aarch64-linux-gnu)
endif()

set(CMAKE_C_COMPILER clang-19)
set(CMAKE_CXX_COMPILER clang++-19)

set(CMAKE_LINKER_TYPE LLD)
