
set(CMAKE_SYSTEM_NAME Windows)
# set(CMAKE_GENERATOR_PLATFORM "ARM64" CACHE INTERNAL "")

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(CMAKE_C_COMPILER_TARGET aarch64-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET aarch64-windows-msvc)
