
set(CMAKE_SYSTEM_NAME Windows)
# set(CMAKE_GENERATOR_PLATFORM "x86_64" CACHE INTERNAL "")

set(CMAKE_C_COMPILER cl)
set(CMAKE_CXX_COMPILER cl)

set(CMAKE_C_COMPILER_TARGET x86_64-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-windows-msvc)
