# spir-v

CPMAddPackage(
    NAME SPIRV-Headers
    GITHUB_REPOSITORY KhronosGroup/SPIRV-Headers
    GIT_TAG 54a521dd130ae1b2f38fef79b09515702d135bdd
    GIT_SHALLOW ON
    GIT_SUBMODULES_RECURSE OFF
    OPTIONS
        "SPIRV_HEADERS_ENABLE_INSTALL ON"
)

CPMAddPackage(
    NAME SPIRV-Tools
    GITHUB_REPOSITORY KhronosGroup/SPIRV-Tools
    GIT_TAG v2025.1.rc1
    GIT_SHALLOW ON
    GIT_SUBMODULES_RECURSE OFF
    OPTIONS
        "SPIRV_WERROR OFF"
)

CPMAddPackage(
    NAME SPIRV-Cross
    GITHUB_REPOSITORY KhronosGroup/SPIRV-Cross
    GIT_TAG vulkan-sdk-1.4.304.1
    GIT_SHALLOW ON
    GIT_SUBMODULES_RECURSE OFF
    OPTIONS
        "SPIRV_CROSS_SHARED ${BUILD_SHARED_LIBS}"
        "SPIRV_CROSS_STATIC ${LSTGEXT_BUILD_STATIC_LIBS}"
        "SPIRV_CROSS_CLI OFF"
        "SPIRV_CROSS_ENABLE_TESTS OFF"
        "SPIRV_CROSS_ENABLE_CPP OFF"
        "SPIRV_CROSS_ENABLE_REFLECT OFF"
        "SPIRV_CROSS_ENABLE_C_API OFF"
)


# directx shader compiler

CPMAddPackage(
    NAME DXC
    GITHUB_REPOSITORY microsoft/DirectXShaderCompiler
    GIT_TAG v1.8.2502
    GIT_SHALLOW ON
    GIT_SUBMODULES_RECURSE OFF
    # OPTIONS
    #     "BUILD_SHARED_LIBS OFF"
    #     "HLSL_ENABLE_DEBUG_ITERATORS ON"
    #     "DXC_COVERAGE OFF"
    #     "HLSL_INCLUDE_TESTS OFF"
    #     "LLVM_INCLUDE_TESTS OFF"
    #     "HLSL_DISABLE_SOURCE_GENERATION TRUE"
    #     "ENABLE_SPIRV_CODEGEN ON"
    DOWNLOAD_ONLY YES
    PATCHES "DXShader.patch"
)

set(_BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS})

set(BUILD_SHARED_LIBS OFF)
set(HLSL_ENABLE_DEBUG_ITERATORS ON)
set(DXC_COVERAGE OFF)
set(HLSL_INCLUDE_TESTS OFF)
set(LLVM_INCLUDE_TESTS OFF)
set(HLSL_DISABLE_SOURCE_GENERATION TRUE)
set(ENABLE_SPIRV_CODEGEN ON)

include(${DXC_SOURCE_DIR}/cmake/caches/PredefinedParams.cmake)
add_subdirectory(${DXC_SOURCE_DIR})

set(BUILD_SHARED_LIBS ${_BUILD_SHARED_LIBS})


# sdl_shadercross

CPMAddPackage(
    NAME SDL_shadercross
    GITHUB_REPOSITORY libsdl-org/SDL_shadercross
    GIT_TAG 63026450dedbf7d8aeee99d9086719f425b2bb4d
    GIT_SUBMODULES_RECURSE OFF
    OPTIONS
        "SDLSHADERCROSS_INSTALL ON"
        "SDLSHADERCROSS_DXC ON"
        "SDLSHADERCROSS_SPIRVCROSS_SHARED ${BUILD_SHARED_LIBS}"
        "SDLSHADERCROSS_SHARED ${BUILD_SHARED_LIBS}"
        "SDLSHADERCROSS_STATIC ${LSTGEXT_BUILD_STATIC_LIBS}"
        "SDLSHADERCROSS_VENDORED OFF"
    PATCHES "SDL_shadercross.patch"
)

if(BUILD_SHARED_LIBS)
    lstgext_tgtopts_full(SDL3_shadercross-shared)
else()
    lstgext_tgtopts_full(SDL3_shadercross-static)
endif()


# glslang

CPMAddPackage(
    NAME glslang
    GITHUB_REPOSITORY KhronosGroup/glslang
    GIT_TAG 15.1.0
    GIT_SHALLOW ON
    GIT_SUBMODULES_RECURSE OFF
    OPTIONS
        "BUILD_EXTERNAL OFF"
        "ENABLE_GLSLANG_JS OFF"
        "ENABLE_HLSL OFF" # use dxc instead
        "ENABLE_SPVREMAPPER OFF"
        "GLSLANG_ENABLE_INSTALL ON"
)
