name: CMake on multiple platforms

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-24.04, windows-latest, macos-14]
        target_arch: [x86_64, arm64]

    steps:
    - run: echo ${{ runner.os }}

    - if: ${{ runner.os == 'Linux' }}
      run: |
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt install \
          ninja-build mesa-utils mesa-common-dev libxext-dev libasound2-dev \
          libgcc-14-dev-arm64-cross libstdc++-14-dev-arm64-cross libssl-dev:arm64
    - if: ${{ runner.os == 'Windows' }}
      run: |
        choco install ninja
        Install-Module -Name VCVars -Confirm:$false -Force
        (vcvars $(switch ("${{ matrix.target_arch }}") { "x86_64" {"AMD64"}; "arm64" {"ARM64"}; })).GetEnumerator()
        | Foreach { "$($_.Key)=$($_.Value)" >> "$GITHUB_ENV" }
    - if: ${{ runner.os == 'macOS' }}
      run: brew install ninja llvm@18

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set reusable strings
      id: strings
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Cache C++ packages
      id: cache-cpp
      uses: actions/cache@v4
      with:
        path: ${{ steps.strings.outputs.build-output-dir }}/cpm-cache
        key: ${{ runner.os }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-cpm-
            
    - name: Configure and Build with CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/toolchain/${{ runner.os }}-${{ matrix.target_arch }}.cmake
        -DCMAKE_BUILD_TYPE=Release
        -S ${{ github.workspace }}
        -DCPM_SOURCE_CACHE=${{ steps.strings.outputs.build-output-dir }}/cpm-cache
        -G Ninja
        &&
        cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release --target ExternalZip

    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: external-${{ runner.os }}-${{ matrix.target_arch }}
        path: |
          ${{ steps.strings.outputs.build-output-dir }}/out/external
        retention-days: 7
