name: CMake on multiple platforms

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        os: [ubuntu-20.04, windows-latest, macos-14]
        target_arch:
          - main: x86_64
            main_win: AMD64
            rev: westmere
            rev_win: SSE4.2
          - main: x86_64
            main_win: AMD64
            rev: haswell
            rev_win: AVX2
          - main: arm64
            main_win: ARM64
            rev: armv8.2-a
            rev_win: armv8.2

    steps:
    - name: Configure Linux (arm)
      if: ${{ runner.os == 'Linux' && matrix.target_arch.main == 'arm64' }}
      run: |
        sudo dpkg --add-architecture arm64
        # sudo sed -i "/Components: /a Architectures: amd64" /etc/apt/sources.list.d/ubuntu.sources
        sudo sed -Ei 's/deb (\w)/deb [arch=amd64] \1/g' /etc/apt/sources.list
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal main restricted"                                | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates main restricted"                        | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal universe"                                       | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates universe"                               | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal multiverse"                                     | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-updates multiverse"                             | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-backports main restricted universe multiverse"  | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-security main restricted"                       | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-security universe"                              | sudo tee -a /etc/apt/sources.list > /dev/null
        echo "deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports focal-security multiverse"                            | sudo tee -a /etc/apt/sources.list > /dev/null
        sudo apt update
        sudo apt install libssl-dev:arm64 gcc-10-aarch64-linux-gnu libstdc++-10-dev-arm64-cross binutils-aarch64-linux-gnu \
          libx11-dev:arm64 libpipewire-0.2-dev:arm64 libwayland-dev:arm64 libaudio-dev:arm64 libjack-dev:arm64 libsndio-dev:arm64 \
          libasound2-dev:arm64 libpulse-dev:arm64 libpulse-mainloop-glib0:arm64 libglib2.0-dev:arm64 libxkbcommon-dev:arm64
    - name: Configure Linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt install \
          ninja-build mesa-utils mesa-common-dev libxext-dev libasound2-dev
        sudo rm -f /usr/bin/clang /usr/bin/clang++
        sudo ln -s /usr/bin/clang-18 /usr/bin/clang
        sudo ln -s /usr/bin/clang++-18 /usr/bin/clang++
        sudo ln -s /usr/bin/ld.lld-18 /usr/bin/ld.lld
    - name: Configure Windows
      if: ${{ runner.os == 'Windows' }}
      run: |
        choco install ninja
        Install-Module -Name VCVars -Confirm:$false -Force
        (vcvars ${{ matrix.target_arch.main_win }}).GetEnumerator()
        | Foreach { "$($_.Key)=$($_.Value)" >> "$env:GITHUB_ENV" }
    - name: Configure macOS
      if: ${{ runner.os == 'macOS' }}
      run: brew install ninja llvm@18 lld

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Cache C++ packages
      id: cache-cpp
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/build/cpm-cache
        key: ${{ runner.os }}-${{ matrix.target_arch.main }}-${{ matrix.target_arch.rev }}-cpm-${{ hashFiles('**/') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.target_arch.main }}-${{ matrix.target_arch.rev }}-cpm-
            
    - name: Configure and Build with CMake
      run: >
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/toolchain/${{ runner.os }}-${{ matrix.target_arch.main }}.cmake
        -DCMAKE_BUILD_TYPE=Release
        -DTARGET_ARCH_REV="${{ matrix.target_arch.rev }}"
        -DTARGET_ARCH_REV_WIN="${{ matrix.target_arch.rev_win }}"
        -DBUILD_SHARED_LIBS=ON
        -S ${{ github.workspace }}
        -DCPM_SOURCE_CACHE=${{ github.workspace }}/build/cpm-cache
        -G Ninja
        &&
        cmake --build ${{ github.workspace }}/build --config Release --target external-build
        &&
        cmake --install ${{ github.workspace }}/build
        &&
        cmake -E rename ${{ github.workspace }}/build/lstgext ${{ github.workspace }}/build/lstgext-shared
        &&
        cmake -B ${{ github.workspace }}/build
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/toolchain/${{ runner.os }}-${{ matrix.target_arch.main }}.cmake
        -DCMAKE_BUILD_TYPE=Release
        -DTARGET_ARCH_REV="${{ matrix.target_arch.rev }}"
        -DTARGET_ARCH_REV_WIN="${{ matrix.target_arch.rev_win }}"
        -DBUILD_SHARED_LIBS=OFF
        -S ${{ github.workspace }}
        -DCPM_SOURCE_CACHE=${{ github.workspace }}/build/cpm-cache
        -G Ninja
        &&
        cmake --build ${{ github.workspace }}/build --config Release --target external-build
        &&
        cmake --install ${{ github.workspace }}/build
        &&
        cmake -E rename ${{ github.workspace }}/build/lstgext ${{ github.workspace }}/build/lstgext-static

    - name: Archive Shared
      uses: actions/upload-artifact@v4
      with:
        name: lstgext-shared-${{ runner.os }}-${{ matrix.target_arch.main }}-${{ matrix.target_arch.rev_win }}
        path: ${{ github.workspace }}/build/lstgext-shared
        retention-days: 7

    - name: Archive Static
      uses: actions/upload-artifact@v4
      with:
        name: lstgext-static-${{ runner.os }}-${{ matrix.target_arch.main }}-${{ matrix.target_arch.rev_win }}
        path: ${{ github.workspace }}/build/lstgext-static
        retention-days: 7
