name: Compile LuaSTG Evo External Dependencies (Stage 1)

on:
  workflow_dispatch:

jobs:
  build-sdl3:
    uses: ./.github/workflows/cmake-multi-platform.yml
    with:
      build: sdl3
      retention: 90
  build-zip:
    uses: ./.github/workflows/cmake-multi-platform.yml
    with:
      build: zip

  cache-sdl3:
    runs-on: ubuntu-latest
    needs: build-sdl3
    steps:
      - uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/${{ github.action_repository }}/actions/variables/SDL3_RUN_ID
          name: SDL3_RUN_ID
          value: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.SDL3_CACHER }}