name: Compile LuaSTG Evo External Dependencies (Stage 2)

on:
  workflow_dispatch:

jobs:
  build-main:
    uses: ./.github/workflows/cmake-multi-platform.yml
    with:
      build: main
      sdl3: true
      sdl3-run-id: ${{ fromJson(vars.SDL3_RUN_ID) }}
    secrets: inherit
  # build-shader:
  #   uses: ./.github/workflows/cmake-multi-platform.yml
  #   with:
  #     build: shader
  #     sdl3: true
  #     sdl3-run-id: ${{ fromJson(vars.SDL3_RUN_ID) }}
  #   secrets: inherit

  bundle-archives:
    runs-on: ubuntu-latest
    needs:
      - build-main
      # - build-shader
    steps:
      - name: Download all Stage 1 workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/lstgext
          github-token: ${{ secrets.SDL3_CACHE }}
          run-id: ${{ vars.SDL3_RUN_ID }}

      - name: Download all Stage 2 workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/lstgext

      - name: Organize and rezip artifacts
        run: |
          cd ${{ github.workspace }}/lstgext/
          for a in */; do
            b=$(echo "$a" | sed -nE 's/lstgext-(.*)-(.*)-(.*)-(.*)-(.*)$/lstgext-\1-\2-\3-\4/gp' -)
            mkdir -p $b/
            cp -rn $a/* $b/
            rm -rf $a
          done
          for a in */; do
            zip -r "${a%/}.zip" "$a" &
          done
          wait

      - name: Archive All
        uses: actions/upload-artifact@v4
        with:
          name: lstgext-all
          path: ${{ github.workspace }}/lstgext/*.zip
          retention-days: 30


