name: Compile LuaSTG Evo External Dependencies (All)

on:
  workflow_dispatch:

jobs:
  build-sdl3:
    uses: ./.github/workflows/cmake-multi-platform.yml
    with:
      build: sdl3
      retention: 90
  build-main:
    uses: ./.github/workflows/cmake-multi-platform.yml
    needs: build-sdl3
    with:
      build: main
      sdl3: true
  build-shader:
    uses: ./.github/workflows/cmake-multi-platform.yml
    needs: build-sdl3
    with:
      build: shader
      sdl3: true
  build-zip:
    uses: ./.github/workflows/cmake-multi-platform.yml
    with:
      build: zip

  cache-sdl3:
    runs-on: ubuntu-latest
    needs: build-sdl3
    steps:
      - uses: octokit/request-action@v2.4.0
        with:
          route: POST /repos/${{ github.action_repository }}/actions/variables/
          name: SDL3_RUN_ID
          value: ${{ github.run_id }}
        env:
          GITHUB_TOKEN: ${{ secrets.SDL3_CACHER }}

  bundle-archives:
    runs-on: ubuntu-latest
    needs:
      - build-sdl3
      - build-main
      - build-shader
      - build-zip
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/lstgext

      - name: Organize and rezip artifacts
        run: |
          cd ${{ github.workspace }}/lstgext/
          for a in */; do
            b=$(echo "$a" | sed -nE 's/lstgext-(.*)-(.*)-(.*)-(.*)-(.*)$/lstgext-\1-\2-\3-\4/gp' -)
            mkdir $b
            mv $a/* $b
            rm $a
          done
          for a in */; do
            zip -r "${a%/}.zip" "$a" &
          done
          wait

      - name: Archive All
        uses: actions/upload-artifact@v4
        with:
          name: lstgext-all
          path: ${{ github.workspace }}/lstgext/*.zip
          retention-days: 30


