name: Compile LuaSTG Evo External Dependencies

on:
  workflow_dispatch:

jobs:
  build-sdl3:
    uses: ./.github/workflows/cmake-multi-platform.yml
    with:
      build: sdl3
  build-main:
    uses: ./.github/workflows/cmake-multi-platform.yml
    with:
      build: main
      sdl3: true
  build-shader:
    uses: ./.github/workflows/cmake-multi-platform.yml
    with:
      build: shader
      sdl3: true
  build-zip:
    uses: ./.github/workflows/cmake-multi-platform.yml
    with:
      build: zip

  bundle-archives:
    runs-on: ubuntu-latest
    needs:
      - build-sdl3
      - build-main
      - build-shader
      - build-zip
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/lstgext

      - name: Organize and rezip artifacts
        run: |
          cd ${{ github.workspace }}/lstgext/
          for a in */
            a_=$(echo "$a" | sed -nE 's/lstgext-(.*)-(.*)-(.*)-(.*)-(.*)$/lstgext-\1-\2-\3-\4/gp' -)
            mkdir $a_
            mv $a/* $a_
            rm $a
          done
          for a in */
            do zip -r "${a%/}.zip" "$a" &
          done
          wait

      - name: Archive All
        uses: actions/upload-artifact@v4
        with:
          name: lstgext-all
          path: ${{ github.workspace }}/lstgext/*.zip
          retention-days: 30


